---
version: 9.7.0.0-rc01
slug: samba
name: Samba share - with interfaces configuration
description: Expose Home Assistant folders with SMB/CIFS
url: https://github.com/lmagyar/homeassistant-addon-samba-interface
codenotary: lmagyar1973@gmail.com
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
host_network: true
image: lmagyar/{arch}-addon-samba-interface
init: false
map:
  - config:rw
  - ssl:rw
  - addons:rw
  - share:rw
  - backup:rw
  - media:rw
options:
  username: homeassistant
  password: null
  workgroup: WORKGROUP
  compatibility_mode: false
  veto_files:
    - ._*
    - .DS_Store
    - Thumbs.db
    - icon?
    - .Trashes
  allow_hosts:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - fe80::/10
  interfaces: []
schema:
  username: str
  password: password
  workgroup: str
  compatibility_mode: bool
  veto_files:
    - str
  allow_hosts:
    - str
  interfaces:
    - str?
startup: services
